# Generated by Django 5.2.2 on 2025-06-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransactionHistory",
            new_name="Transaction",
        ),
    ]
