# Generated by Django 5.2.2 on 2025-06-11 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_rename_account_id_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
