# Generated by Django 5.2.2 on 2025-06-11 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("WEEKLY", "주간"), ("MONTHLY", "월간")], max_length=10
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("description", models.TextField()),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="analysis/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
