name: Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04

    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Packages & Libraries
        run: |
          uv pip install --system -r requirements.txt

      - name: Create secret directory
        run: mkdir -p .config_secret

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "secret.json"
          json: ${{ secrets.SECRET_JSON }}
          dir: '.config_secret'

      - name: Run isort (Import sorting)
        run: |
          uv run isort . --check --diff

      - name: Run black (Code formatting)
        run: |
          uv run black . --check

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U ${{ secrets.PG_USER }}; do
            sleep 1
          done

      - name: Run Django Migration
        run: |
          uv run python manage.py makemigrations
          uv run python manage.py migrate

      - name: Test python project
        run: |
          uv run python manage.py test